vimplugin:
  prefix: "vimplugin"
  body: |
    ${1:name} = pkgs.vimUtils.buildVimPlugin {
      name = "$1";
      src = pkgs.fetchFromGitHub {
        owner = "${2:owner}";
        repo = "${3:repo}";
        rev = "${4:main}";
        hash = "${5:}";
      };
    };
