[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"

[plugins.git-auto-fetch]
remote = "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/plugins/git-auto-fetch/git-auto-fetch.plugin.zsh"
