require("configs.command")
require("configs.option")
require("configs.keymap")
require("configs.autocmd")

require("plugins.lspconfig")
require("plugins.gitsigns")
require("plugins.cmp")
require("plugins.fidget-nvim")
require("plugins.toggleterm")
