require("configs.command")
require("configs.option")
require("configs.keymap")
require("configs.autocmd")

require("plugins.goyo")
require("plugins.ddu")
require("plugins.ddc")
require("plugins.lspconfig")
require("plugins.gitsigns")
require("plugins.lsp")
