#!/usr/bin/env bash

if ps -a | grep wofi >/dev/null; then
  killall -q wofi
else
  case $(printf "%s\n" "󰐥 p: POWER OFF" "󰑐 r: RESTART" "󰖔 s: SUSPEND" "󰌾 l: LOCK" "󰗽 o: LOG OUT" | wofi --show=dmenu --hide-scroll --allow-markup --define=hide_search --width=600 --height=200) in
  "󰐥 p: POWER OFF")
    systemctl poweroff
    ;;
  "󰑐 r: RESTART")
    systemctl reboot
    ;;
  "󰖔 s: SUSPEND")
    systemctl suspend
    ;;
  "󰌾 l: LOCK")
    swaylock
    ;;
  "󰗽 o: LOG OUT")
    hyprctl dispatch exit 1
    ;;
  esac
fi
